version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    ignore:
        # Synchronised with Minecraft
      - dependency-name: "com.google.code.gson:gson"
        # Synchronised with Minecraft
      - dependency-name: "com.google.guava:guava"
        # Requires Java 17
      - dependency-name: "com.puppycrawl.tools:checkstyle"
        update-types: ["version-update:semver-major"]
        # Requires Java 17
      - dependency-name: "org.apache.maven:maven-resolver-provider"
        update-types: ["version-update:semver-major"]
        # Requires Java 11
      - dependency-name: "org.jline:jline"
        update-types: ["version-update:semver-major"]
        # Requires Java 17
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
