/*
 * Copyright 2011 Király Attila
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.cage;

/**
 * Factory creating {@link IGenerator}s.
 * 
 * @param <T>
 *            the type of objects generated by the generators created by this
 *            object.
 * 
 * @author akiraly
 */
public interface IGeneratorFactory<T> extends IGenerator<IGenerator<T>> {
}
